# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 784777b46574bc586ef1a4169c3abdbbc2cb930779c6042fd69ad08fdc30770d17f7682ce9d995828f684d72151a1af21c83ee51678ed851e6dbd897982e49ea

test:
  secret_key_base: 0eb1fcecefb9289ea956ed3c13eb6d2037ac7ca37331fa36cff483fe71b139edc2bd75f051f169c59ef7adaa3cf969f2c0614dfcf8426b4617e61e1b6a56431c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
